version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    depends_on:
      - ollama
      - db
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
  
  frontend:
    build:
      context: ./frontend
    image: react-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  ollama:
    image: ollama/ollama:latest  # Use the official image directly
    container_name: ollama
    # For NVIDIA GPUs (ignored if not available)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # For AMD/Intel GPUs
    devices:
      - /dev/dri:/dev/dri  # Generic GPU access, ignored if doesn't exist
    ports:
      - "11434:11434"
    volumes:
      - ./llm/models:/root/.ollama/models
  
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
