version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    depends_on:
      - db
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      # - DATABASE_URL=postgresql://user:password@host.docker.internal:5432/mydatabase
  frontend:
    build:
      context: ./frontend
    image: react-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
