version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
  frontend:
    build:
      context: ./frontend
    image: react-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11434:11434"
    volumes:
      - ./llm/models:/root/.ollama/models
    command: ["serve"]
