version: '3.8'
services:
  backend:
    build:
      context: ./backend
      # dockerfile: ./backend/Dockerfile
    image: fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8001:8001"
    depends_on:
      - ollama
      - db
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DATABASE_URL=postgresql://user:password@host.docker.internal:5432/mydatabase
  frontend:
    build:
      context: ./frontend
    image: react-frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  ollama:
    build:
      context: ./ollama
    image: custom-ollama
    container_name: ollama
    # Try to include all possible devices that might be needed
    devices:
      - /dev/dri:/dev/dri  # For AMD/Intel GPUs (ignored if doesn't exist)
    # Add nvidia runtime but make it optional
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ./llm/models:/root/.ollama/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
